source('code/revision_2026/common.R')
setDTthreads(2)
dest<-file.path(revision_dir,'lung_composite_sensitivity')
d<-readRDS(file.path(revision_dir,'cache','lung_composite','intervals.rds'))
setorder(d,PERS_ID,tstart)
stopifnot(!anyNA(d$lung_composite),all(is.finite(d$lung_composite)),all(d$score_source_date<=d$start_date),all(d$tstop>d$tstart))
z<-d[,.(continuous=all(tstart[-1]==head(tstop,-1)),starts_at_zero=min(tstart)==0,events=sum(tv_adverse_event)),by=PERS_ID]
stopifnot(all(z$continuous),all(z$starts_at_zero),all(z$events<=1))
r<-fread(file.path(dest,'supplement_results.csv'))
e<-fread(file.path(dest,'era_effects_from_interaction_models.csv'))
v<-fread(file.path(dest,'original_model_replication.csv'))
stopifnot(nrow(r)==56,nrow(e)==12,all(e$status=='OK'),!anyDuplicated(r[,.(model,subgroup,term)]),all(abs(v$original_HR-v$replicated_HR)<1e-6))
stopifnot(all(r[model %in% c('Single pollutant','PM2.5 + NO2','PM2.5 + NO2 + O3'),status]=='OK'))
cat('Composite timing, continuity, replication and complete reporting tests passed.\n')
